log-handlers:
    Exp:
        path_prefix: "/data/log/output"
        file_prefix: "Exp_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    LevelUp:
        path_prefix: "/data/log/output"
        file_prefix: "Levelup_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    Currency:
        path_prefix: "/data/log/output"
        file_prefix: "Currency_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    Object:
        path_prefix: "/data/log/output"
        file_prefix: "Object_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    HeroUpStar:
        path_prefix: "/data/log/output"
        file_prefix: "HeroUpStar_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    HeroWake:
        path_prefix: "/data/log/output"
        file_prefix: "HeroWake_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    Train:
        path_prefix: "/data/log/output"
        file_prefix: "Train_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    Manufacture:
        path_prefix: "/data/log/output"
        file_prefix: "Manufacture_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    ExchangeCurrency:
        path_prefix: "/data/log/output"
        file_prefix: "ExchangeCurrency_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    Market:
        path_prefix: "/data/log/output"
        file_prefix: "Market_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    UnlockPack:
        path_prefix: "/data/log/output"
        file_prefix: "UnlockPack_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    FriendSys:
        path_prefix: "/data/log/output"
        file_prefix: "FriendSys_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    SevenDay:
        path_prefix: "/data/log/output"
        file_prefix: "SevenDay_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    Sign:
        path_prefix: "/data/log/output"
        file_prefix: "Sign_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    LevelReward:
        path_prefix: "/data/log/output"
        file_prefix: "LevelReward_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    GiftBag:
        path_prefix: "/data/log/output"
        file_prefix: "GiftBag_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    AutoObj:
        path_prefix: "/data/log/output"
        file_prefix: "AutoObj_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    Trade:
        path_prefix: "/data/log/output"
        file_prefix: "Trade_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    TradeOperate:
        path_prefix: "/data/log/output"
        file_prefix: "TradeOperate_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    UseDrug:
        path_prefix: "/data/log/output"
        file_prefix: "UseDrug_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    Guild:
        path_prefix: "/data/log/output"
        file_prefix: "Guild_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    Task:
        path_prefix: "/data/log/output"
        file_prefix: "Task_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    GuildFinance:
        path_prefix: "/data/log/output"
        file_prefix: "GuildFinance_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    SGRoom:
        path_prefix: "/data/log/output"
        file_prefix: "SGRoom_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    ChangeTask:
        path_prefix: "/data/log/output"
        file_prefix: "ChangeTask_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    Online:
        path_prefix: "/data/log/output"
        file_prefix: "Online_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    Team:
        path_prefix: "/data/log/output"
        file_prefix: "Team_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    Mail:
        path_prefix: "/data/log/output"
        file_prefix: "Mail_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    DoublePoint:
        path_prefix: "/data/log/output"
        file_prefix: "DoublePoint_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    PKRank:
        path_prefix: "/data/log/output"
        file_prefix: "PKRank_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    ChangeLine:
        path_prefix: "/data/log/output"
        file_prefix: "ChangeLine_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    ChangeMap:
        path_prefix: "/data/log/output"
        file_prefix: "ChangeMap_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    OnVehicle:
        path_prefix: "/data/log/output"
        file_prefix: "OnVehicle_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    PublishMaster:
        path_prefix: "/data/log/output"
        file_prefix: "PublishMaster_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    EducationChanged:
        path_prefix: "/data/log/output"
        file_prefix: "EducationChanged_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    OverApprentice:
        path_prefix: "/data/log/output"
        file_prefix: "OverApprentice_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    ThanksLetter:
        path_prefix: "/data/log/output"
        file_prefix: "ThanksLetter_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    DailyTaskReward:
        path_prefix: "/data/log/output"
        file_prefix: "DailyTaskReward_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    MissionStatus:
        path_prefix: "/data/log/output"
        file_prefix: "MissionStatus_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    ThanksLetterReward:
        path_prefix: "/data/log/output"
        file_prefix: "ThanksLetterReward_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    ThanksLetterFeedback:
        path_prefix: "/data/log/output"
        file_prefix: "ThanksLetterFeedback_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    FastMatch:
        path_prefix: "/data/log/output"
        file_prefix: "FastMatch_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    SevenGoal:
        path_prefix: "/data/log/output"
        file_prefix: "SevenGoal_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    Achievement:
        path_prefix: "/data/log/output"
        file_prefix: "Achievement_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    PlayerVatility:
        path_prefix: "/data/log/output"
        file_prefix: "PlayerVatility_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    ApprenticeVitality:
        path_prefix: "/data/log/output"
        file_prefix: "ApprenticeVitality_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    AnswerQuestTool:
        path_prefix: "/data/log/output"
        file_prefix: "AnswerQuestTool_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    QuitPlotMap:
        path_prefix: "/data/log/output"
        file_prefix: "QuitPlotMap_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    ChangeHero:
        path_prefix: "/data/log/output"
        file_prefix: "ChangeHero_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    PlayerDeath:
        path_prefix: "/data/log/output"
        file_prefix: "PlayerDeath_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    PlayerMatch:
        path_prefix: "/data/log/output"
        file_prefix: "PlayerMatch_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    RegainAward:
        path_prefix: "/data/log/output"
        file_prefix: "RegainAward_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    FinishFight:
        path_prefix: "/data/log/output"
        file_prefix: "FinishFight_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    UserDispatch:
        path_prefix: "/data/log/output"
        file_prefix: "UserDispatch_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    GuildVitality:
        path_prefix: "/data/log/output"
        file_prefix: "GuildVitality_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    AddApprentice:
        path_prefix: "/data/log/output"
        file_prefix: "AddApprentice_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    PlayerGuild:
        path_prefix: "/data/log/output"
        file_prefix: "PlayerGuild_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    AddPotencyExp:
        path_prefix: "/data/log/output"
        file_prefix: "AddPotencyExp_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    GetEquipObject:
        path_prefix: "/data/log/output"
        file_prefix: "GetEquipObject_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    OpEquipWithEquipPage:
        path_prefix: "/data/log/output"
        file_prefix: "OpEquipWithEquipPage_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    ChangeEquipPageName:
        path_prefix: "/data/log/output"
        file_prefix: "ChangeEquipPageName_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    ChangeHeroEquipPage:
        path_prefix: "/data/log/output"
        file_prefix: "ChangeHeroEquipPage_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    AddEquipPage:
        path_prefix: "/data/log/output"
        file_prefix: "AddEquipPage_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    DayOnlineTime:
        path_prefix: "/data/log/output"
        file_prefix: "DayOnlineTime_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    Login:
        path_prefix: "/data/log/output"
        file_prefix: "Login_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    Logout:
        path_prefix: "/data/log/output"
        file_prefix: "Logout_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    EquipStrengthUp:
        path_prefix: "/data/log/output"
        file_prefix: "EquipStrengthUp_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    SwitchEquipStrength:
        path_prefix: "/data/log/output"
        file_prefix: "SwitchEquipStrength_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    SuccRewardDrop:
        path_prefix: "/data/log/output"
        file_prefix: "SuccRewardDrop_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    PolishEquip:
        path_prefix: "/data/log/output"
        file_prefix: "PolishEquip_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    ActiveEquipPolish:
        path_prefix: "/data/log/output"
        file_prefix: "ActiveEquipPolish_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    IdentifyEquip:
        path_prefix: "/data/log/output"
        file_prefix: "IdentifyEquip_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    UserActivity:
        path_prefix: "/data/log/output"
        file_prefix: "UserActivity_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    GuildPartyStart:
        path_prefix: "/data/log/output"
        file_prefix: "GuildPartyStart_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    GuildPartyOP:
        path_prefix: "/data/log/output"
        file_prefix: "GuildPartyOP_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    SaveUser:
        path_prefix: "/data/log/output"
        file_prefix: "SaveUser_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    TillDie:
        path_prefix: "/data/log/output"
        file_prefix: "TillDie_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    DrawLottery:
        path_prefix: "/data/log/output"
        file_prefix: "DrawLottery_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    Recharge:
        path_prefix: "/data/log/output"
        file_prefix: "Recharge_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    MonthCard:
        path_prefix: "/data/log/output"
        file_prefix: "MonthCard_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    MonthCardReward:
        path_prefix: "/data/log/output"
        file_prefix: "MonthCardReward_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    UserAttr:
        path_prefix: "/data/log/output"
        file_prefix: "UserAttr_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    Compose:
        path_prefix: "/data/log/output"
        file_prefix: "Compose_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    MakeObj:
        path_prefix: "/data/log/output"
        file_prefix: "MakeObj_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    ObserveOtherUser:
        path_prefix: "/data/log/output"
        file_prefix: "ObserveOtherUser_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    GuildNewSkill:
        path_prefix: "/data/log/output"
        file_prefix: "GuildNewSkill_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

    DonateGuildResource:
        path_prefix: "/data/log/output"
        file_prefix: "DonateGuildResource_"
        file_suffix: ".log"
        split_time_col: 2
        split_minutes: 5

